version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - environment/.tsenv
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./data:/home
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file:
      - ./environment/.gfenv
    volumes:
      - ./grafana:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning

volumes:
  db:
    driver: local